spring:
  application:
    name: GooInProAdminAPI
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://gooinprodb.chw6wee6k3li.ap-northeast-2.rds.amazonaws.com:13307/gooinprodb
    username: gooinprodbuser
    password: gooinprodbuser


    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      connection-timeout: 5000

  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDB103Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

org:
  gooinpro:
    accessTime: 1
    refreshTime: 10000
    alwaysNew: true